project:
  type: website
  output-dir: docs

website:
  title: "Ruben Jimenez"
  navbar:
    background: dark
    style: inverse
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - resume.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true


