project:
  type: website
  output-dir: docs

website:
  title: "Ruben Jimenez: Statistician Extraordinaire"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme:
      light: lux
      dark: lux
    css: styles.css
    toc: true



